use std::collections::BTreeMap;
use std::ffi::OsString;
use std::fs;
use std::path::Path;
use std::process::{Command, Output, Stdio};

use reporigor_reporting::ReportEnvelope;

#[test]
fn generic_and_native_rust_share_nested_function_semantics() {
    let project = tempfile::tempdir().unwrap_or_else(|error| panic!("fixture: {error}"));
    fs::create_dir(project.path().join("src")).unwrap_or_else(|error| panic!("source directory: {error}"));
    fs::write(
        project.path().join("Cargo.toml"),
        "[package]\nname='function-semantics'\nversion='0.0.0'\nedition='2021'\npublish=false\n",
    )
    .unwrap_or_else(|error| panic!("manifest: {error}"));
    fs::write(
        project.path().join("Cargo.lock"),
        "# This file is automatically @generated by Cargo.\nversion = 3\n\n[[package]]\nname = \"function-semantics\"\nversion = \"0.0.0\"\n",
    )
    .unwrap_or_else(|error| panic!("lockfile: {error}"));
    fs::write(
        project.path().join("src/lib.rs"),
        r"pub fn outer(flag: bool) -> bool {
    fn local(value: bool) -> bool {
        if value { loop { break; } }
        value
    }
    let deferred = |value: bool| {
        if value { while value { break; } }
        value
    };
    if flag { deferred(flag) } else { false }
}

pub fn sibling() -> bool { true }
",
    )
    .unwrap_or_else(|error| panic!("Rust source: {error}"));

    let generic = run_crap("generic", "rust", project.path());
    let native = run_crap("native", "rust", project.path());
    let expected = BTreeMap::from([("outer".to_string(), 2), ("sibling".to_string(), 1)]);
    assert_eq!(function_complexities(&generic), expected);
    assert_eq!(function_complexities(&native), expected);
}

#[test]
fn generic_and_native_clang_share_cpp_lambda_semantics() {
    if !command_available("clang") {
        eprintln!("skipping C++ function-semantics test because clang is unavailable");
        return;
    }

    let project = tempfile::tempdir().unwrap_or_else(|error| panic!("fixture: {error}"));
    fs::create_dir(project.path().join("src")).unwrap_or_else(|error| panic!("source directory: {error}"));
    fs::write(
        project.path().join("src/sample.cpp"),
        r"int outer(int value) {
  auto deferred = [](int inner) {
    if (inner > 0) { while (inner > 1) { --inner; } }
    return inner;
  };
  if (value > 0) { return deferred(value); }
  return 0;
}

int sibling() { return 1; }
",
    )
    .unwrap_or_else(|error| panic!("C++ source: {error}"));
    let database = serde_json::json!([{
        "directory": project.path(),
        "file": "src/sample.cpp",
        "arguments": ["clang++", "-std=c++17", "-c", "src/sample.cpp"]
    }]);
    fs::write(
        project.path().join("compile_commands.json"),
        serde_json::to_vec(&database).unwrap_or_else(|error| panic!("database JSON: {error}")),
    )
    .unwrap_or_else(|error| panic!("compilation database: {error}"));

    let generic = run_crap("generic", "cpp", project.path());
    let native = run_crap("native", "cpp", project.path());
    let expected = BTreeMap::from([("outer".to_string(), 2), ("sibling".to_string(), 1)]);
    assert_eq!(function_complexities(&generic), expected);
    assert_eq!(function_complexities(&native), expected);
}

fn run_crap(backend: &str, language: &str, root: &Path) -> ReportEnvelope {
    let mut arguments = vec![OsString::from("--backend"), OsString::from(backend)];
    if backend == "native" {
        arguments.push(OsString::from("--allow-project-exec"));
    }
    arguments.extend([
        OsString::from("--language"),
        OsString::from(language),
        OsString::from("--format"),
        OsString::from("json"),
        OsString::from("crap"),
        OsString::from("--allow-missing-coverage"),
        root.as_os_str().to_owned(),
    ]);
    let output = Command::new(env!("CARGO_BIN_EXE_reporigor"))
        .args(arguments)
        .stdin(Stdio::null())
        .output()
        .unwrap_or_else(|error| panic!("run reporigor: {error}"));
    assert_success(&output, &format!("{backend} {language}"));
    serde_json::from_slice(&output.stdout).unwrap_or_else(|error| {
        panic!(
            "{backend} {language} returned invalid JSON: {error}\nstdout:\n{}\nstderr:\n{}",
            String::from_utf8_lossy(&output.stdout),
            String::from_utf8_lossy(&output.stderr)
        )
    })
}

fn function_complexities(report: &ReportEnvelope) -> BTreeMap<String, u32> {
    report
        .results
        .crap
        .as_ref()
        .unwrap_or_else(|| panic!("CRAP section is missing"))
        .functions
        .iter()
        .map(|function| (function.name.clone(), function.complexity))
        .collect()
}

fn command_available(program: &str) -> bool {
    Command::new(program)
        .arg("--version")
        .stdin(Stdio::null())
        .stdout(Stdio::null())
        .stderr(Stdio::null())
        .status()
        .is_ok_and(|status| status.success())
}

fn assert_success(output: &Output, context: &str) {
    assert!(
        output.status.success(),
        "{context} failed with {:?}\nstdout:\n{}\nstderr:\n{}",
        output.status.code(),
        String::from_utf8_lossy(&output.stdout),
        String::from_utf8_lossy(&output.stderr)
    );
}
