use std::error::Error;
use std::ffi::OsString;
use std::fs;
use std::path::Path;
use std::process::{Command, Output};

#[test]
fn auto_rust_falls_back_only_for_native_parse_failures() -> Result<(), Box<dyn Error>> {
    let project = tempfile::tempdir()?;
    fs::create_dir(project.path().join("src"))?;
    fs::write(
        project.path().join("Cargo.toml"),
        "[package]\nname = \"rust-partial-fallback\"\nversion = \"0.1.0\"\nedition = \"2021\"\n",
    )?;
    fs::write(
        project.path().join("Cargo.lock"),
        "# This file is automatically @generated by Cargo.\n# It is not intended for manual editing.\nversion = 3\n\n[[package]]\nname = \"rust-partial-fallback\"\nversion = \"0.1.0\"\n",
    )?;
    fs::write(
        project.path().join("src/lib.rs"),
        "pub fn retained() -> bool { true }\npub fn broken( { false }\n",
    )?;

    let automatic = run(check_arguments("auto", project.path(), true))?;
    assert_success(&automatic, "automatic Rust partial fallback");
    let automatic: serde_json::Value = serde_json::from_slice(&automatic.stdout)?;
    assert_eq!(automatic["summary"]["files"], 1);
    assert!(automatic["results"]["crap"]["functions"]
        .as_array()
        .is_some_and(|functions| functions.iter().any(|function| function["name"] == "retained")));
    for backend in ["rust-native", "tree-sitter-generic"] {
        assert!(automatic["backends"]
            .as_array()
            .is_some_and(|backends| backends.iter().any(|item| item["id"] == backend)));
    }
    let native_fallbacks = automatic["diagnostics"]
        .as_array()
        .into_iter()
        .flatten()
        .filter(|diagnostic| {
            diagnostic["backend"] == "rust-native"
                && diagnostic["fallback_used"] == true
                && diagnostic["location"]["file"] == "src/lib.rs"
        })
        .count();
    assert_eq!(
        native_fallbacks, 1,
        "native fallback diagnostic must not be duplicated"
    );

    let generic = run(check_arguments("generic", project.path(), false))?;
    assert_success(&generic, "generic Rust parse-error reference");
    let generic: serde_json::Value = serde_json::from_slice(&generic.stdout)?;
    assert_eq!(
        automatic["summary"]["parse_errors"], generic["summary"]["parse_errors"],
        "native placeholder and generic parse errors were both counted"
    );

    let native = run(check_arguments("native", project.path(), true))?;
    assert_eq!(native.status.code(), Some(1));
    assert!(String::from_utf8(native.stderr)?.contains("generic fallback"));
    Ok(())
}

fn check_arguments(backend: &str, root: &Path, allow_exec: bool) -> Vec<OsString> {
    let mut arguments = vec![OsString::from("--backend"), OsString::from(backend)];
    if allow_exec {
        arguments.push(OsString::from("--allow-project-exec"));
    }
    arguments.extend([
        OsString::from("--language"),
        OsString::from("rust"),
        OsString::from("--allow-parse-errors"),
        OsString::from("--format"),
        OsString::from("json"),
        OsString::from("check"),
        OsString::from("--min-tokens"),
        OsString::from("1000"),
        root.as_os_str().to_owned(),
    ]);
    arguments
}

fn run(arguments: impl IntoIterator<Item = OsString>) -> Result<Output, std::io::Error> {
    Command::new(env!("CARGO_BIN_EXE_reporigor"))
        .args(arguments)
        .output()
}

fn assert_success(output: &Output, context: &str) {
    assert!(
        output.status.success(),
        "{context} failed\nstdout:\n{}\nstderr:\n{}",
        String::from_utf8_lossy(&output.stdout),
        String::from_utf8_lossy(&output.stderr)
    );
}
