use std::fs;
use std::path::{Path, PathBuf};

use tempfile::{tempdir, TempDir};

use reporigor_core::MutationCandidate;

pub(crate) fn is_logical_flip(candidate: &MutationCandidate) -> bool {
    candidate.original == "&&" && candidate.replacement == "||"
}

pub(crate) fn project(package: &str, source: &str) -> TempDir {
    let directory = temporary();
    write_basic_project(directory.path(), package, source);
    directory
}

pub(crate) fn temporary_subdirectory(name: &str) -> (TempDir, PathBuf) {
    let directory = temporary();
    let path = directory.path().join(name);
    create_directory(&path, "temporary subdirectory");
    (directory, path)
}

pub(crate) fn temporary() -> TempDir {
    tempdir().unwrap_or_else(|error| panic!("fixture: {error}"))
}

pub(crate) fn project_with_file(package: &str, source: &str, relative: &str, contents: &str) -> TempDir {
    let directory = project(package, source);
    let path = directory.path().join(relative);
    if let Some(parent) = path.parent() {
        create_directory(parent, "supplemental source directory");
    }
    write_file(&path, contents, "supplemental source");
    directory
}

pub(crate) fn aliased_module_project(package: &str, function: &str) -> TempDir {
    project_with_file(
        package,
        "#[path=\"shared.rs\"] mod alpha;\n#[path=\"shared.rs\"] mod beta;\n",
        "src/shared.rs",
        function,
    )
}

pub(crate) fn required<'a, T>(items: &'a [T], label: &str, predicate: impl Fn(&T) -> bool) -> &'a T {
    items
        .iter()
        .find(|item| predicate(item))
        .unwrap_or_else(|| panic!("{label} missing"))
}

pub(crate) fn write_basic_project(root: &Path, package: &str, source: &str) {
    create_directory(&root.join("src"), "create source directory");
    write_manifest(root, package, "");
    write_lock(root, package);
    write_file(&root.join("src/lib.rs"), source, "root source");
}

pub(crate) fn write_manifest(root: &Path, package: &str, suffix: &str) {
    let manifest = format!("[package]\nname='{package}'\nversion='0.1.0'\nedition='2021'\n{suffix}");
    write_file(&root.join("Cargo.toml"), &manifest, "manifest");
}

pub(crate) fn write_lock(root: &Path, package: &str) {
    let lockfile = format!(
        "# This file is automatically @generated by Cargo.\n# It is not intended for manual editing.\nversion = 3\n\n[[package]]\nname = \"{package}\"\nversion = \"0.1.0\"\n"
    );
    write_file(&root.join("Cargo.lock"), &lockfile, "lockfile");
}

pub(crate) fn create_directory(path: &Path, label: &str) {
    fs::create_dir_all(path).unwrap_or_else(|error| panic!("{label}: {error}"));
}

pub(crate) fn write_file(path: &Path, contents: impl AsRef<[u8]>, label: &str) {
    fs::write(path, contents).unwrap_or_else(|error| panic!("{label}: {error}"));
}

pub(crate) fn read_file(path: impl AsRef<Path>, label: &str) -> String {
    fs::read_to_string(path).unwrap_or_else(|error| panic!("{label}: {error}"))
}

#[cfg(unix)]
pub(crate) fn executable(root: &Path, name: &str, source: &str) -> PathBuf {
    use std::os::unix::fs::PermissionsExt;

    let program = root.join(name);
    write_file(&program, source, "fake program");
    let mut permissions = fs::metadata(&program)
        .unwrap_or_else(|error| panic!("fake program metadata: {error}"))
        .permissions();
    permissions.set_mode(0o755);
    fs::set_permissions(&program, permissions)
        .unwrap_or_else(|error| panic!("fake program permissions: {error}"));
    program
}
